CREATE TABLE  "PRESUPUESTO_GASTO" 
   (	
    "OBLIGACION_PENDIENTE_PAGO" NUMBER, 
	"CREDITO_MODIFICACION" NUMBER, 
	"ORGANO" VARCHAR2(450), 
	"ID_ORGANO" VARCHAR2(450), 
	"OBLIGACION_NETA" NUMBER, 
	"ID" VARCHAR2(450), 
	"FECHA" VARCHAR2(450), 
	"CONCEPTO" VARCHAR2(450), 
	"PARTIDA" VARCHAR2(450), 
	"ID_CAPITULO" NUMBER, 
	"CREDITO_DEFINITIVO" NUMBER, 
	"CAPITULO" VARCHAR2(450), 
	"CREDITO_INICIAL" NUMBER, 
	"ID_AREA" VARCHAR2(450), 
	"PAGO_NETO" NUMBER, 
	"GASTO_COMPROMETIDO" NUMBER, 
	"REMANENTE_DE_CREDITO" NUMBER, 
	"AREA" VARCHAR2(450)
   ) ;
/
CREATE TABLE  "PRESUPUESTO_INGRESO" 
   (	
    "APLICACION" VARCHAR2(450), 
	"DERECHOS_CANCELADOS" NUMBER, 
	"EXCESO_DEFECTO_PREVISION" NUMBER, 
	"DERECHOS_RECONOCIDOS_NETOS" NUMBER, 
	"PREVISION_MODIFICACION" NUMBER, 
	"DERECHOS_RECONOCIDOS" NUMBER, 
	"ID" VARCHAR2(450), 
	"RECAUDACION_NETA" NUMBER, 
	"FECHA" VARCHAR2(450), 
	"PREVISION_INICIAL" NUMBER, 
	"CONCEPTO" VARCHAR2(450), 
	"ID_CAPITULO" NUMBER, 
	"CAPITULO" VARCHAR2(450), 
	"DERECHOS_ANULADOS_Y_DEVOL" NUMBER, 
	"PREVISION_DEFINITIVO" NUMBER, 
	"DERECHOS_PENDIENTES_COBRO" NUMBER
   ) ;
 /
 